In [10]:
import pandas as pd
import numpy as np
import os, pdb, sys, pickle

with open('results.pkl', 'rb') as f: 
    dct = pickle.load(f)
dct.keys()

dict_keys(['0.001-30', '0.01-30', '0.1-30', '0.6-30', '1.0-30', '5-30', '10-30', '20-30', '30-30'])

In [11]:
df = {}
for key in dct.keys(): 
    name = key.split('-')[0]
    sub = dct[key][['x1', 'x2', 'x3']]
    reg = sub.iloc[:1000]
    drf = sub.iloc[1000:]
    df[name] = {'reg': reg, 'drf': drf}
print(df.keys())

dict_keys(['0.001', '0.01', '0.1', '0.6', '1.0', '5', '10', '20', '30'])

In [21]:
ks, meanReg, meanDrf, minReg, minDrf, maxReg, maxDrf, varReg, varDrf = [], [], [], [], [], [], [], [], []

for k in df.keys(): 
    reg = df[k]['reg']
    drf = df[k]['drf']
    ks.append(k)
    meanReg.append(np.nanmean(reg['x1']))
    meanDrf.append(np.nanmean(drf['x1']))
    minReg.append(min(reg['x1']))
    minDrf.append(min(drf['x1']))
    maxReg.append(max(reg['x1']))
    maxDrf.append(max(drf['x1']))
    varReg.append(np.var(reg['x1']))
    varDrf.append(np.var(drf['x1']))

res = pd.DataFrame({'shock': ks, 'mean_base': meanReg, 'mean_shocked': meanDrf, 
                   'min_base': minReg, 'min_shocked': minDrf, 
                   'max_base': maxReg, 'max_shocked': maxDrf, 
                   'var_base': varReg, 'var_shocked': varDrf})
res

,shock,mean_base,mean_shocked,min_base,min_shocked,max_base,max_shocked,var_base,var_shocked
0,0.001,0.019332,0.000021,-3.241267,-0.002929,3.852731,0.003243,0.957905,0.000001
1,0.01,0.019332,0.000061,-3.241267,-0.031767,3.852731,0.031129,0.957905,0.000102
2,0.1,0.019332,-0.004869,-3.241267,-0.271261,3.852731,0.277996,0.957905,0.009771
3,0.6,0.019332,-0.002027,-3.241267,-2.213019,3.852731,1.719127,0.957905,0.386608
4,1.0,0.019332,-0.000692,-3.241267,-2.520847,3.852731,2.240927,0.957905,0.880971
5,5,0.019332,-0.033213,-3.241267,-14.053142,3.852731,14.006865,0.957905,23.105002
6,10,0.019332,-0.229156,-3.241267,-30.339894,3.852731,26.024799,0.957905,111.017928
7,20,0.019332,2.079241,-3.241267,-49.413266,3.852731,68.578210,0.957905,429.601690
8,30,0.019332,0.026982,-3.241267,-99.885114,3.852731,72.550673,0.957905,970.806298